#!/bin/bash
i=`echo -e "logout\nshutdown\nreboot" | rofi -p "" -dmenu` 
if [ "$i" = "logout" ]
then
   confirm=`echo -e "Yes\nNo" | rofi -p "Do you want to logout?" -dmenu` 
   if [ $confirm = "Yes" ]
   then
       openbox --exit
   else
       echo "No" >> /dev/null
   fi
elif [ "$i" = "shutdown" ]
then
   confirm=`echo -e "Yes\nNo" | rofi -p "Do you want to shutdown?" -dmenu` 
   if [ $confirm = "Yes" ]
   then
       shutdown now
   else
       echo "No" >> /dev/null
   fi
elif [ "$i" = "reboot" ]
then
   confirm=`echo -e "Yes\nNo" | rofi -p "Do you want to reboot?" -dmenu` 
   if [ $confirm = "Yes" ]
   then
       reboot
   else
       echo "No" >> /dev/null
   fi
fi
